# Generated by Django 5.2.8 on 2025-12-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0004_locality_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locality',
            name='locality',
            field=models.CharField(max_length=60),
        ),
    ]
