# Generated by Django 5.2.8 on 2025-12-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0005_alter_locality_locality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='type',
            field=models.CharField(max_length=65),
        ),
    ]
