# Generated by Django 5.2.8 on 2025-12-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0006_representation_location_unique_slug_website_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='show',
            constraint=models.UniqueConstraint(fields=('slug', 'created_in'), name='unique_slug_created_in'),
        ),
    ]
